### ISSUE TITLE
Merch v0.5

### ISSUE THREAD

**Issue by rauhul** [acm-uiuc/merch#3]
Issues we need to resolve in order to bring up a Merch MVP

**Hardware**
- [ ]  [add license headers to all the source files in hardware](https://github.com/acm-uiuc/merch-hardware/issues/15)
- [x]  [Explore getting machine state directly from control board](https://github.com/acm-uiuc/merch-hardware/issues/17)
- [x]  [Add port vend sensor mount to source control](https://github.com/acm-uiuc/merch-hardware/issues/18)
- [ ]  [Design Merch faceplate](https://github.com/acm-uiuc/merch-hardware/issues/19)
- [x]  [Breakout machine limit switch signals](https://github.com/acm-uiuc/merch-hardware/issues/20)

**Embebbed**
- [ ]  [Initialize Merch Controller in a context bug](https://github.com/acm-uiuc/merch-embedded/issues/15)
- [ ]  [Tracking machine state bug help wanted](https://github.com/acm-uiuc/merch-hardware/issues/14)
